version: "3.8"
services: 
  fairag3:
    container_name: fairag3
    build:
      context: .
      args:
        - JULIA_VERSION=1.6.3
    ports: 
      - "4321:1234"
    volumes: 
      - .:/home/julia/project
